name: tests
on:
  push:
    branches: ['*']
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: run tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m doctest docchat.py